# Executed on every push by GitHub Actions. 
# This runs CI tests

on: [push]

name: build

jobs:

  linux-macos-win:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
        include:
          - {name: Linux, python: '3.9', os: ubuntu-latest}
    env:
      CIBW_TEST_COMMAND:
        PYTHONWARNINGS=always PYTHONUNBUFFERED=1 PSUTIL_TESTING=1 PSUTIL_DEBUG=1 python {project}/unitest.py &&
        PYTHONWARNINGS=always PYTHONUNBUFFERED=1 PSUTIL_TESTING=1 PSUTIL_DEBUG=1 python {project}/unitest-restful.py &&
        PYTHONWARNINGS=always PYTHONUNBUFFERED=1 PSUTIL_TESTING=1 PSUTIL_DEBUG=1 python {project}/unitest-xmlrpc.py
      CIBW_TEST_EXTRAS: test
      CIBW_SKIP: cp35-* pp*

    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install cibuildwheel
      run: pip install cibuildwheel

    - name: Run tests
      run: cibuildwheel .

    - name: Create wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: wheelhouse

  freebsd:
    runs-on: macos-latest
    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    - name: Run tests
      id: test
      uses: vmactions/freebsd-vm@v0.0.8
      with:
        usesh: true
        prepare: pkg install -y gcc python3
        run: |
          set +e
          export \
            PYTHONUNBUFFERED=1 \
            PYTHONWARNINGS=always \
            PSUTIL_TESTING=1 \
            PSUTIL_DEBUG=1
          python3 -m pip install --user setuptools
          python3 setup.py install
          python3 unitest.py
          python3 unitest-restful.py
          python3 unitest-xmlrpc.py*

  linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: 'Run linters'
      run: |
        python2 -m pip install flake8
        python3 -m pip install flake8
        python2 -m flake8 .
        python3 -m flake8 .
        echo "flake8 linting OK"
