# Executed on every push by GitHub Actions. 
# This runs CI tests

on: [push]

name: build

jobs:

  linux-macos-win:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    # env:
    #   CIBW_TEST_COMMAND:
    #     PYTHONWARNINGS=always PYTHONUNBUFFERED=1 PSUTIL_TESTING=1 PSUTIL_DEBUG=1 python {project}/unitest.py &&
    #     PYTHONWARNINGS=always PYTHONUNBUFFERED=1 PSUTIL_TESTING=1 PSUTIL_DEBUG=1 python {project}/unitest-restful.py &&
    #     PYTHONWARNINGS=always PYTHONUNBUFFERED=1 PSUTIL_TESTING=1 PSUTIL_DEBUG=1 python {project}/unitest-xmlrpc.py
    #   CIBW_TEST_EXTRAS: test
    #   CIBW_SKIP: cp35-* pp*

    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install cibuildwheel
      run: pip install cibuildwheel

    - name: Create wheels
      run: python -m cibuildwheel --output-dir wheelhouse

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: wheelhouse

  linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: 'Run linters'
      run: |
        python3 -m pip install flake8
        python3 -m flake8 .
        echo "Flake8 linting OK"
